# Generated by Django 3.2.14 on 2022-07-22 08:43

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Child',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('birthday', models.DateField(null=True)),
                ('email', models.EmailField(max_length=256)),
                ('mobile', models.CharField(max_length=13)),
                ('grade', models.CharField(max_length=20, null=True)),
                ('school_name', models.CharField(max_length=250, null=True)),
                ('school_address', models.CharField(max_length=256, null=True)),
                ('hobbies', models.TextField(max_length=20, null=True)),
                ('aspirations', models.TextField(null=True)),
                ('profile', models.ImageField(null=True, upload_to='img')),
            ],
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('code', models.CharField(max_length=256, unique=True)),
                ('icon_url', models.CharField(blank=True, max_length=256)),
                ('is_active', models.BooleanField(default=True)),
                ('created_by', models.CharField(max_length=256)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('last_updated_by', models.CharField(max_length=256)),
                ('last_updated_date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='EnumChildStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('status', models.CharField(max_length=256)),
                ('description', models.CharField(max_length=256)),
                ('is_active', models.BooleanField(default=True)),
                ('created_by', models.CharField(max_length=256)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('last_updated_by', models.CharField(max_length=256)),
                ('last_updated_date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='EnumChildType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('type', models.CharField(max_length=256)),
                ('description', models.CharField(max_length=256)),
                ('is_active', models.BooleanField(default=True)),
                ('created_by', models.CharField(max_length=256)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('last_updated_by', models.CharField(max_length=256)),
                ('last_updated_date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='EnumDocumentType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('type', models.CharField(max_length=256)),
                ('description', models.CharField(max_length=256)),
                ('is_active', models.BooleanField(default=True)),
                ('created_by', models.CharField(max_length=256)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('last_updated_by', models.CharField(max_length=256)),
                ('last_updated_date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='EnumGender',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('gender', models.CharField(max_length=1)),
                ('description', models.CharField(max_length=256)),
                ('is_active', models.BooleanField(default=True)),
                ('created_by', models.CharField(max_length=256)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('last_updated_by', models.CharField(max_length=256)),
                ('last_updated_date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='EnumUserRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(max_length=256)),
                ('name', models.CharField(max_length=256)),
                ('description', models.CharField(max_length=256)),
                ('is_active', models.BooleanField(default=True)),
                ('created_by', models.CharField(max_length=256)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('last_updated_by', models.CharField(max_length=256)),
                ('last_updated_date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='KidDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('birthday', models.DateField(blank=True, null=True)),
                ('age', models.IntegerField(blank=True)),
                ('email', models.EmailField(blank=True, max_length=250, null=True)),
                ('mobile', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region=None, unique=True)),
                ('profile', models.ImageField(blank=True, null=True, upload_to='img')),
                ('grade', models.CharField(blank=True, max_length=20, null=True)),
                ('school', models.CharField(blank=True, max_length=250, null=True)),
                ('school_address', models.CharField(blank=True, max_length=256, null=True)),
                ('hobbies', models.TextField(blank=True, max_length=20, null=True)),
                ('aspirations', models.TextField(blank=True, null=True)),
                ('achievements', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_by', models.CharField(max_length=256)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('last_updated_by', models.CharField(max_length=256)),
                ('last_updated_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('child_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bright_life_app.enumchildtype')),
                ('gender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bright_life_app.enumgender')),
                ('status', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='bright_life_app.enumchildstatus')),
            ],
        ),
        migrations.CreateModel(
            name='GuardianDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profession', models.CharField(blank=True, max_length=256, null=True)),
                ('annual_income', models.FloatField(blank=True, null=True)),
                ('family_member', models.CharField(blank=True, max_length=256)),
                ('extra_allowance', models.FloatField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_by', models.CharField(max_length=256)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('last_updated_by', models.CharField(max_length=256)),
                ('last_updated_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('kid_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bright_life_app.kiddetails')),
            ],
        ),
        migrations.CreateModel(
            name='CountryState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('code', models.CharField(max_length=256, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_by', models.CharField(max_length=256)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('last_updated_by', models.CharField(max_length=256)),
                ('last_updated_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('country_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bright_life_app.country')),
            ],
        ),
        migrations.CreateModel(
            name='ChildDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('document', models.FileField(upload_to='doc/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'doc', 'img', 'png', 'jpeg'])])),
                ('is_active', models.BooleanField(default=True)),
                ('created_by', models.CharField(max_length=256)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('last_updated_by', models.CharField(max_length=256)),
                ('last_updated_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('child_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bright_life_app.child')),
                ('document_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bright_life_app.enumdocumenttype')),
            ],
        ),
        migrations.CreateModel(
            name='ChildAchievement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('description', models.CharField(max_length=256)),
                ('is_active', models.BooleanField(default=True)),
                ('created_by', models.CharField(max_length=256)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('last_updated_by', models.CharField(max_length=256)),
                ('last_updated_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('child_document_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bright_life_app.childdocument')),
                ('child_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bright_life_app.child')),
            ],
        ),
        migrations.AddField(
            model_name='child',
            name='child_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bright_life_app.enumchildtype'),
        ),
        migrations.AddField(
            model_name='child',
            name='status',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='bright_life_app.enumchildstatus'),
        ),
        migrations.CreateModel(
            name='BankAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bank_name', models.CharField(blank=True, max_length=256, null=True)),
                ('state', models.CharField(blank=True, max_length=256, null=True)),
                ('postal_code', models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinLengthValidator(6), django.core.validators.MaxLengthValidator(6)])),
                ('account_holder', models.CharField(blank=True, max_length=20, null=True, unique=True)),
                ('account_number', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinLengthValidator(9), django.core.validators.MaxLengthValidator(18)])),
                ('branch', models.CharField(max_length=256, null=True)),
                ('ifsc', models.CharField(max_length=11, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_by', models.CharField(max_length=256)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('last_updated_by', models.CharField(max_length=256)),
                ('last_updated_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('kid_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bright_life_app.kiddetails')),
            ],
        ),
    ]
