# Generated by Django 3.2.14 on 2022-07-14 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Kid',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('birthday', models.DateField(help_text='Enter your birthday')),
                ('age', models.IntegerField()),
                ('email', models.EmailField(max_length=250)),
                ('phone', models.CharField(help_text='countryCode - mobile', max_length=15)),
            ],
        ),
    ]
