# Generated by Django 3.2.14 on 2022-07-14 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bright_life_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kid',
            name='phone',
            field=models.CharField(max_length=15, unique=True),
        ),
    ]
