# Generated by Django 3.2.14 on 2022-07-14 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bright_life_app', '0002_alter_kid_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kid',
            name='phone',
            field=models.IntegerField(max_length=10, unique=True),
        ),
    ]
