# Generated by Django 3.2.14 on 2022-07-16 12:37

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bright_life_app', '0003_alter_kid_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kid',
            name='phone',
            field=models.IntegerField(unique=True, validators=[django.core.validators.MinLengthValidator(10), django.core.validators.MaxLengthValidator(13)]),
        ),
    ]
